FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir boto3

COPY evtxkit/ ./evtxkit/
COPY soccore/ ./soccore/
COPY s3_wrapper.py .

ENTRYPOINT ["python3", "s3_wrapper.py"]

CMD ["--help"]