"""
evtxkit test suite.

Run with: python tests/test_evtxkit.py    (or: python -m pytest tests/ -q)

Samples live in samples/ (generated by make_events.py, run automatically by
setUpModule if the directory is missing) -- one small JSON-Lines event set
per detector scenario, plus clean_baseline.jsonl / clean_baseline_
ConsoleHost_history.txt which must trip *nothing* and regression-test
every rule's false-positive surface at once.
"""

from __future__ import annotations

import os
import subprocess
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import evtxkit
from evtxkit.config import Config
from evtxkit.detectors import REGISTRY, run_detectors
from evtxkit.detectors.base import Detector, register
from evtxkit.models import EventRecord, Finding
from evtxkit.parsers import (
    _xml_to_event_record,
    detect_format,
    parse_jsonl_file,
    parse_jsonl_line,
    parse_powershell_history,
)
from evtxkit.processtree import ProcessTree, events_for_logon_id, find_logon_event
from evtxkit.report import render
from evtxkit.util import (
    any_substring,
    has_double_extension,
    is_private_or_reserved_ip,
    is_removable_drive_path,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SAMPLES = os.path.join(ROOT, "samples", "evtxkit")


def setUpModule():
    if not os.path.isdir(SAMPLES) or not os.listdir(SAMPLES):
        subprocess.run([sys.executable, os.path.join(ROOT, "tools", "make_evtx_events.py"), SAMPLES],
                        cwd=ROOT, check=True)


def _p(name: str) -> str:
    return os.path.join(SAMPLES, name)


def _rule_ids(result) -> set:
    return {f.rule_id for f in result.findings}


def _analyze(name: str, config: Config | None = None):
    return evtxkit.analyze(_p(name), config=config)


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------
class TestUtil(unittest.TestCase):
    def test_private_ip_rfc1918(self):
        self.assertTrue(is_private_or_reserved_ip("10.0.5.12"))
        self.assertTrue(is_private_or_reserved_ip("172.16.4.4"))
        self.assertTrue(is_private_or_reserved_ip("192.168.1.1"))

    def test_loopback_and_unspecified(self):
        self.assertTrue(is_private_or_reserved_ip("127.0.0.1"))
        self.assertTrue(is_private_or_reserved_ip("0.0.0.0"))
        self.assertTrue(is_private_or_reserved_ip(""))
        self.assertTrue(is_private_or_reserved_ip("not-an-ip"))

    def test_documentation_ranges_count_as_external(self):
        # RFC 5737 ranges (this project's own synthetic "attacker" IPs
        # throughout nsmkit/trafkit/waapkit) must NOT be treated as
        # private -- see util.py's docstring for why the stdlib's own
        # ip.is_private is the wrong tool for this check.
        for ip in ("203.0.113.77", "198.51.100.9", "192.0.2.44"):
            self.assertFalse(is_private_or_reserved_ip(ip), f"{ip} wrongly treated as private")

    def test_real_public_ip_is_external(self):
        self.assertFalse(is_private_or_reserved_ip("8.8.8.8"))

    def test_any_substring(self):
        self.assertEqual(any_substring("whoami /priv", ("whoami", "net user")), "whoami")
        self.assertIsNone(any_substring("Get-Process", ("whoami", "net user")))
        self.assertIsNone(any_substring("", ("whoami",)))

    def test_double_extension(self):
        self.assertTrue(has_double_extension("C:\\Users\\v\\Downloads\\invoice.pdf.exe"))
        self.assertFalse(has_double_extension("C:\\Users\\v\\Downloads\\invoice.pdf"))
        self.assertFalse(has_double_extension("C:\\Windows\\System32\\cmd.exe"))

    def test_removable_drive_path(self):
        self.assertTrue(is_removable_drive_path("E:\\malware.exe", tuple("DEFG")))
        self.assertFalse(is_removable_drive_path("C:\\Windows\\System32\\cmd.exe", tuple("DEFG")))
        self.assertFalse(is_removable_drive_path("relative\\path.exe", tuple("DEFG")))


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------
class TestParsers(unittest.TestCase):
    def test_jsonl_line_basic(self):
        import json
        obj = {"EventID": 4625, "Channel": "Security", "TimeCreated": "2026-09-06T10:00:00+00:00",
                "Computer": "WIN01", "EventData": {"TargetUserName": "admin", "LogonType": 10, "IpAddress": "1.2.3.4"}}
        e = parse_jsonl_line(json.dumps(obj), 0)
        self.assertEqual(e.event_id, 4625)
        self.assertEqual(e.channel, "Security")
        self.assertEqual(e.target_user, "admin")
        self.assertEqual(e.logon_type, 10)
        self.assertEqual(e.source_ip, "1.2.3.4")
        self.assertGreater(e.ts, 0)

    def test_jsonl_malformed_returns_none(self):
        self.assertIsNone(parse_jsonl_line("not json", 0))
        self.assertIsNone(parse_jsonl_line("   ", 0))

    def test_jsonl_sysmon_channel_normalized(self):
        import json
        obj = {"EventID": 1, "Channel": "Microsoft-Windows-Sysmon/Operational", "EventData": {}}
        e = parse_jsonl_line(json.dumps(obj), 0)
        self.assertEqual(e.channel, "Sysmon")

    def test_xml_event_record(self):
        xml = (
            '<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">'
            '<System><EventID>4624</EventID><Channel>Security</Channel>'
            '<Computer>WIN01</Computer>'
            '<TimeCreated SystemTime="2026-09-06T10:15:03.1234567Z"/></System>'
            '<EventData><Data Name="TargetUserName">Administrator</Data>'
            '<Data Name="LogonType">10</Data></EventData></Event>'
        )
        rec = _xml_to_event_record(xml, 0)
        self.assertEqual(rec.event_id, 4624)
        self.assertEqual(rec.channel, "Security")
        self.assertEqual(rec.target_user, "Administrator")
        self.assertEqual(rec.logon_type, 10)
        self.assertGreater(rec.ts, 0)

    def test_xml_malformed_returns_none(self):
        self.assertIsNone(_xml_to_event_record("<not><valid", 0))

    def test_xml_element_with_only_text_is_not_falsy(self):
        # regression: `elem_a or elem_b` on ElementTree Elements is a trap
        # -- an Element with text but no children is falsy under bool(),
        # so a naive `or`-chained find() would silently discard a real
        # match. EventID here is exactly that shape (all text, no
        # children), so this test fails if that trap creeps back in.
        xml = (
            '<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">'
            '<System><EventID>1</EventID><Channel>Sysmon</Channel></System>'
            '<EventData></EventData></Event>'
        )
        rec = _xml_to_event_record(xml, 0)
        self.assertEqual(rec.event_id, 1)

    def test_powershell_history_parsing(self):
        events = parse_powershell_history(_p("discovery_ConsoleHost_history.txt"))
        self.assertGreater(len(events), 0)
        self.assertTrue(all(e.channel == "PowerShellHistory" for e in events))
        self.assertTrue(all(e.ts == 0.0 for e in events))

    def test_detect_format(self):
        self.assertEqual(detect_format("foo.evtx"), "evtx")
        self.assertEqual(detect_format("ConsoleHost_history.txt"), "pshistory")
        self.assertEqual(detect_format("events.jsonl"), "jsonl")

    def test_parse_jsonl_file(self):
        events = parse_jsonl_file(_p("clean_baseline.jsonl"))
        self.assertEqual(len(events), 6)


# ---------------------------------------------------------------------------
# Process tree / logon correlation
# ---------------------------------------------------------------------------
class TestProcessTree(unittest.TestCase):
    def test_ancestry_chain(self):
        events = parse_jsonl_file(_p("discovery.jsonl"))
        tree = ProcessTree(events)
        # the last discovery step (wmic) should trace back through cmd.exe to invoice.pdf.exe
        wmic_event = next(e for e in events if e.image.lower().endswith("wmic.exe"))
        ancestry = tree.ancestry(wmic_event)
        images = [a.image for a in ancestry]
        self.assertIn("C:\\Windows\\System32\\cmd.exe", images)
        root = tree.root_of(wmic_event)
        self.assertTrue(root.image.lower().endswith("invoice.pdf.exe"))

    def test_children_of(self):
        events = parse_jsonl_file(_p("discovery.jsonl"))
        tree = ProcessTree(events)
        cmd_event = next(e for e in events if e.image.lower().endswith("\\cmd.exe") and e.process_guid == "{guid-cmd}")
        children = tree.children_of(cmd_event)
        self.assertGreaterEqual(len(children), 6)

    def test_events_for_logon_id_and_find_logon_event(self):
        events = parse_jsonl_file(_p("backdoor_user.jsonl"))
        matches = events_for_logon_id(events, "0x9f3a21")
        self.assertEqual(len(matches), 5)
        logon = find_logon_event(events, "0x9f3a21")
        self.assertIsNotNone(logon)
        self.assertEqual(logon.target_user, "Administrator")

    def test_events_for_missing_logon_id(self):
        events = parse_jsonl_file(_p("backdoor_user.jsonl"))
        self.assertEqual(events_for_logon_id(events, ""), [])
        self.assertEqual(events_for_logon_id(events, "0xdeadbeef"), [])


# ---------------------------------------------------------------------------
# Detector registry / isolation
# ---------------------------------------------------------------------------
class TestDetectorRegistry(unittest.TestCase):
    def test_registry_nonempty_and_unique_ids(self):
        self.assertGreater(len(REGISTRY), 10)
        ids = [d.id for d in REGISTRY]
        self.assertEqual(len(ids), len(set(ids)), f"duplicate detector ids: {ids}")

    def test_broken_detector_does_not_crash_the_run(self):
        @register
        class _BoomDetector(Detector):
            id = "TEST-BOOM"
            title = "boom"
            tactic = "Unknown"

            def run(self, events, tree):
                raise RuntimeError("boom")

        try:
            findings = run_detectors([], Config())
            self.assertTrue(any(f.rule_id == "TEST-BOOM-ERROR" for f in findings))
        finally:
            REGISTRY.remove(_BoomDetector)


# ---------------------------------------------------------------------------
# Per-detector positive cases
# ---------------------------------------------------------------------------
class TestLogonDetectors(unittest.TestCase):
    def test_rdp_brute_force_and_success(self):
        ids = _rule_ids(_analyze("rdp_brute_force.jsonl"))
        self.assertIn("EVTX-LOGON-BRUTE-01", ids)
        self.assertIn("EVTX-LOGON-BRUTE-SUCCESS-01", ids)

    def test_internal_failed_logons_not_counted(self):
        # clean_baseline.jsonl has one internal-IP 4625 -- must not trip
        # brute force even though it's technically a failed logon.
        ids = _rule_ids(_analyze("clean_baseline.jsonl"))
        self.assertNotIn("EVTX-LOGON-BRUTE-01", ids)


class TestUserManagementDetectors(unittest.TestCase):
    def test_all_user_management_rules_fire(self):
        ids = _rule_ids(_analyze("backdoor_user.jsonl"))
        for expected in ("EVTX-USER-NEW-01", "EVTX-USER-BACKDOOR-ADMIN-01",
                          "EVTX-USER-GROUP-01", "EVTX-USER-PWRESET-01"):
            self.assertIn(expected, ids, f"missing {expected} in {sorted(ids)}")

    def test_backdoor_admin_correlates_creator_source_ip(self):
        result = _analyze("backdoor_user.jsonl")
        new_user_findings = [f for f in result.findings if f.rule_id == "EVTX-USER-NEW-01"]
        self.assertEqual(len(new_user_findings), 1)
        self.assertEqual(new_user_findings[0].evidence.get("creator_source_ip"), "203.0.113.77")


class TestPersistenceDetectors(unittest.TestCase):
    def test_service_task_startup_runkey_all_fire(self):
        ids = _rule_ids(_analyze("persistence.jsonl"))
        for expected in ("EVTX-PERSIST-SERVICE-01", "EVTX-PERSIST-TASK-01",
                          "EVTX-PERSIST-STARTUP-01", "EVTX-PERSIST-RUNKEY-01"):
            self.assertIn(expected, ids, f"missing {expected} in {sorted(ids)}")

    def test_service_in_suspicious_dir_is_high_severity(self):
        result = _analyze("persistence.jsonl")
        service_findings = [f for f in result.findings if f.rule_id == "EVTX-PERSIST-SERVICE-01"]
        self.assertEqual(len(service_findings), 1)
        self.assertEqual(service_findings[0].severity, "high")


class TestExecutionDetectors(unittest.TestCase):
    def test_double_extension_and_downloaded_attachment(self):
        ids = _rule_ids(_analyze("phishing_attachment.jsonl"))
        self.assertIn("EVTX-EXEC-DOUBLEEXT-01", ids)
        self.assertIn("EVTX-EXEC-DOWNLOADED-ATTACHMENT-01", ids)

    def test_lnk_phishing(self):
        ids = _rule_ids(_analyze("lnk_phishing.jsonl"))
        self.assertIn("EVTX-EXEC-LNK-PHISHING-01", ids)

    def test_lnk_phishing_also_reads_as_tool_transfer(self):
        # the room's own chain is LNK -> PowerShell -> download RemcosRAT;
        # both detectors firing on the same event set is the intended
        # cross-tactic overlap, not double-counting.
        ids = _rule_ids(_analyze("lnk_phishing.jsonl"))
        self.assertIn("EVTX-C2-TRANSFER-01", ids)

    def test_removable_drive_execution(self):
        ids = _rule_ids(_analyze("usb_execution.jsonl"))
        self.assertIn("EVTX-EXEC-REMOVABLE-01", ids)

    def test_lnk_detector_needs_a_preceding_drop(self):
        # a script host launched by explorer.exe with NO preceding .lnk
        # file-create event must not be flagged -- otherwise this would
        # fire on every normal PowerShell session a user opens by hand.
        events = [
            EventRecord(index=0, event_id=1, channel="Sysmon", ts=1000.0,
                         data={"Image": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                                "ParentImage": "C:\\Windows\\explorer.exe", "CommandLine": "powershell.exe"}),
        ]
        findings = run_detectors(events, Config())
        self.assertNotIn("EVTX-EXEC-LNK-PHISHING-01", {f.rule_id for f in findings})


class TestDiscoveryDetector(unittest.TestCase):
    def test_discovery_sequence_from_sysmon(self):
        ids = _rule_ids(_analyze("discovery.jsonl"))
        self.assertIn("EVTX-DISCOVERY-SEQ-01", ids)

    def test_discovery_sequence_from_powershell_history(self):
        ids = _rule_ids(_analyze("discovery_ConsoleHost_history.txt"))
        self.assertIn("EVTX-DISCOVERY-SEQ-01", ids)

    def test_single_isolated_command_does_not_fire(self):
        ids = _rule_ids(_analyze("clean_baseline.jsonl"))
        self.assertNotIn("EVTX-DISCOVERY-SEQ-01", ids)


class TestCollectionDetectors(unittest.TestCase):
    def test_all_collection_rules_fire(self):
        ids = _rule_ids(_analyze("collection.jsonl"))
        for expected in ("EVTX-COLLECT-SENSITIVE-01", "EVTX-COLLECT-ARCHIVE-01",
                          "EVTX-COLLECT-CREDSEARCH-01", "EVTX-COLLECT-STEALER-01"):
            self.assertIn(expected, ids, f"missing {expected} in {sorted(ids)}")

    def test_stealer_detector_needs_no_command_line(self):
        # by construction: the stealer scenario's file-create events carry
        # no CommandLine at all -- if this passes, the detector really is
        # command-line-independent as designed.
        events = parse_jsonl_file(_p("collection.jsonl"))
        stealer_events = [e for e in events if e.image == "C:\\Users\\victim\\AppData\\Local\\Temp\\upd.exe"]
        self.assertTrue(stealer_events)
        self.assertTrue(all(not e.command_line for e in stealer_events))


class TestC2Detectors(unittest.TestCase):
    def test_ingress_transfer_and_suspicious_network(self):
        ids = _rule_ids(_analyze("c2_transfer.jsonl"))
        self.assertIn("EVTX-C2-TRANSFER-01", ids)
        self.assertIn("EVTX-C2-SUSPICIOUS-NETWORK-01", ids)

    def test_transfer_correlated_with_network_is_higher_confidence(self):
        result = _analyze("c2_transfer.jsonl")
        transfer = [f for f in result.findings if f.rule_id == "EVTX-C2-TRANSFER-01"]
        self.assertEqual(len(transfer), 1)
        self.assertEqual(transfer[0].severity, "high")
        self.assertEqual(len(transfer[0].events), 2)


class TestCleanBaseline(unittest.TestCase):
    """The mandatory negative case: ordinary admin/user activity must
    never trip a single detector."""

    def test_jsonl_clean_baseline_zero_findings(self):
        result = _analyze("clean_baseline.jsonl")
        self.assertEqual(result.findings, [], f"unexpected findings: {[f.rule_id for f in result.findings]}")
        self.assertEqual(result.worst_severity, "info")

    def test_powershell_history_clean_baseline_zero_findings(self):
        result = _analyze("clean_baseline_ConsoleHost_history.txt")
        self.assertEqual(result.findings, [], f"unexpected findings: {[f.rule_id for f in result.findings]}")


# ---------------------------------------------------------------------------
# Report rendering
# ---------------------------------------------------------------------------
class TestReport(unittest.TestCase):
    def test_render_all_formats_smoke(self):
        result = _analyze("backdoor_user.jsonl")
        for fmt in ("console", "json", "markdown", "html"):
            out = render(result, fmt)
            self.assertIsInstance(out, str)
            self.assertGreater(len(out), 0)

    def test_render_unknown_format_raises(self):
        result = _analyze("backdoor_user.jsonl")
        with self.assertRaises(ValueError):
            render(result, "yaml")

    def test_json_report_round_trips(self):
        import json
        result = _analyze("backdoor_user.jsonl")
        payload = json.loads(render(result, "json"))
        self.assertEqual(payload["event_count"], len(result.events))
        self.assertEqual(len(payload["findings"]), len(result.findings))

    def test_timeline_is_chronological(self):
        from evtxkit.report import _earliest_ts, _timeline
        result = _analyze("backdoor_user.jsonl")
        timeline = _timeline(result)
        tss = [_earliest_ts(result, f) for f in timeline]
        self.assertEqual(tss, sorted(tss))


# ---------------------------------------------------------------------------
# CLI smoke test (subprocess, exit codes)
# ---------------------------------------------------------------------------
class TestCli(unittest.TestCase):
    def _run(self, *args):
        return subprocess.run(
            [sys.executable, "-m", "evtxkit.cli", *args],
            cwd=ROOT, capture_output=True, text=True,
        )

    def test_analyze_exit_code_reflects_severity(self):
        clean = self._run("analyze", _p("clean_baseline.jsonl"))
        self.assertEqual(clean.returncode, 0)
        attack = self._run("analyze", _p("rdp_brute_force.jsonl"))
        self.assertEqual(attack.returncode, 1)

    def test_rules_command(self):
        proc = self._run("rules")
        self.assertEqual(proc.returncode, 0)
        self.assertIn("EVTX-LOGON-BRUTE", proc.stdout)

    def test_overview_command(self):
        proc = self._run("overview", _p("clean_baseline.jsonl"))
        self.assertEqual(proc.returncode, 0)
        self.assertIn("Events:", proc.stdout)

    def test_sessions_command(self):
        proc = self._run("sessions", _p("backdoor_user.jsonl"), "0x9f3a21")
        self.assertEqual(proc.returncode, 0)
        self.assertIn("mr.backd00r", proc.stdout)


# ---------------------------------------------------------------------------
# Ingestion formats beyond JSON-Lines
# ---------------------------------------------------------------------------
class TestIngestionFormats(unittest.TestCase):
    def _write(self, name: str, content: str) -> str:
        import tempfile
        d = tempfile.mkdtemp()
        path = os.path.join(d, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        self.addCleanup(lambda: __import__("shutil").rmtree(d, ignore_errors=True))
        return path

    def test_event_viewer_xml_export_with_userdata(self):
        from evtxkit.parsers import parse_event_file
        events = parse_event_file(_p("log_cleared.xml"))
        self.assertEqual(len(events), 3)
        cleared = next(e for e in events if e.event_id == 1102)
        self.assertEqual(cleared.channel, "Security")
        self.assertEqual(cleared.subject_user, "mr.backd00r")          # read from UserData
        self.assertEqual(cleared.provider, "Microsoft-Windows-Eventlog")
        self.assertEqual(cleared.get("EventRecordID"), "1")

    def test_winlogbeat_ecs_shape(self):
        import json
        obj = {"@timestamp": "2026-09-06T10:00:00.000Z",
               "winlog": {"event_id": 4625, "channel": "Security", "computer_name": "DC01",
                          "event_data": {"TargetUserName": "admin", "LogonType": "10",
                                         "IpAddress": "203.0.113.9"}}}
        e = parse_jsonl_line(json.dumps(obj), 0)
        self.assertEqual((e.event_id, e.channel, e.computer, e.target_user),
                         (4625, "Security", "DC01", "admin"))
        self.assertGreater(e.ts, 0)

    def test_evtx_dump_shape(self):
        import json
        obj = {"Event": {"System": {"EventID": 4688, "Channel": "Security", "Computer": "PC7",
                                    "TimeCreated": {"#attributes": {"SystemTime": "2026-09-06T10:00:00.1234567Z"}}},
                         "EventData": {"NewProcessName": "C:\\Windows\\System32\\whoami.exe",
                                       "NewProcessId": "0x10", "ProcessId": "0x8"}}}
        e = parse_jsonl_line(json.dumps(obj), 0)
        self.assertEqual(e.event_id, 4688)
        self.assertEqual(e.image, "C:\\Windows\\System32\\whoami.exe")
        self.assertEqual((e.process_id, e.parent_process_id), ("16", "8"))

    def test_evtxecmd_payload_and_splunk_raw_xml(self):
        import json
        payload = json.dumps({"EventData": {"Data": [{"@Name": "TargetUserName", "#text": "bob"},
                                                      {"@Name": "LogonType", "#text": "3"}]}})
        e = parse_jsonl_line(json.dumps({"EventId": 4624, "Channel": "Security",
                                         "TimeCreated": "2026-09-06 10:00:00.1234567",
                                         "Payload": payload}), 0)
        self.assertEqual((e.target_user, e.logon_type), ("bob", 3))
        raw = ("<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System>"
               "<EventID>7045</EventID><Channel>System</Channel></System><EventData>"
               "<Data Name='ServiceName'>evilsvc</Data></EventData></Event>")
        e2 = parse_jsonl_line(json.dumps({"_time": "x", "_raw": raw}), 0)
        self.assertEqual((e2.event_id, e2.get("ServiceName")), (7045, "evilsvc"))

    def test_json_array_file(self):
        import json
        from evtxkit.parsers import parse_event_file
        path = self._write("events.json", json.dumps([
            {"EventID": 4625, "Channel": "Security", "TimeCreated": "2026-09-06T10:00:00Z",
             "EventData": {"TargetUserName": "a"}},
            {"EventID": 4625, "Channel": "Security", "TimeCreated": "2026-09-06T10:00:01Z",
             "EventData": {"TargetUserName": "b"}},
        ]))
        self.assertEqual([e.target_user for e in parse_event_file(path)], ["a", "b"])

    def test_get_winevent_positional_json_is_explained_not_misparsed(self):
        import json
        from evtxkit.parsers import EventParseError
        with self.assertRaises(EventParseError) as ctx:
            parse_jsonl_line(json.dumps({"Id": 4624, "LogName": "Security",
                                         "Properties": [{"Value": "S-1-5-18"}]}), 0)
        self.assertIn(".evtx", str(ctx.exception))

    def test_naive_timestamps_are_utc(self):
        from evtxkit.parsers import _parse_iso_ts
        self.assertEqual(_parse_iso_ts("2026-09-06T10:00:00"), _parse_iso_ts("2026-09-06T10:00:00Z"))
        self.assertEqual(_parse_iso_ts("/Date(1788602400000)/"), 1788602400.0)

    def test_sniff_format(self):
        from evtxkit.parsers import sniff_format
        self.assertEqual(sniff_format(b"ElfFile\x00" + b"\x00" * 100), "evtx")
        self.assertEqual(sniff_format(b'<?xml version="1.0"?><Events><Event xmlns='), "xml")
        self.assertEqual(sniff_format(b'{"EventID": 1}'), "jsonl")
        self.assertIsNone(sniff_format(b"2025-08-25 00:47:46 ALLOW TCP 1.2.3.4:1 -> 10.0.0.1:2"))

    @unittest.skipUnless(os.name == "nt", "native .evtx reading uses Windows' wevtutil")
    def test_real_evtx_via_wevtutil(self):
        import shutil
        import tempfile
        from evtxkit.parsers import parse_event_file
        d = tempfile.mkdtemp(prefix="evtx test ")          # a space in the path on purpose
        self.addCleanup(lambda: shutil.rmtree(d, ignore_errors=True))
        path = os.path.join(d, "slice.evtx")
        proc = subprocess.run(["wevtutil", "epl", "Application", path,
                               "/q:*[System[TimeCreated[timediff(@SystemTime) <= 604800000]]]"],
                              capture_output=True)
        if proc.returncode != 0 or not os.path.exists(path):
            self.skipTest("could not export a slice of the local Application log")
        events = parse_event_file(path)
        self.assertTrue(all(e.channel == "Application" and e.ts > 0 for e in events))
        # Application-log event 1 is some provider's event 1, never Sysmon.
        self.assertFalse(any(e.is_process_create for e in events))


# ---------------------------------------------------------------------------
# Channel awareness + Security 4688 coverage
# ---------------------------------------------------------------------------
class TestSecurityOnlyCoverage(unittest.TestCase):
    def test_system_event_1_is_not_process_creation(self):
        e = EventRecord(index=0, event_id=1, channel="System", ts=1.0,
                        data={"Image": "C:\\x.exe", "CommandLine": "whoami"})
        self.assertFalse(e.is_process_create)
        sysmon = EventRecord(index=1, event_id=1, channel="Sysmon", ts=1.0, data={"Image": "C:\\x.exe"})
        self.assertTrue(sysmon.is_process_create)

    def test_4688_pid_mapping_and_process_tree(self):
        events = parse_jsonl_file(_p("security_only.jsonl"))
        tree = ProcessTree(events)
        whoami = next(e for e in events if e.image.endswith("whoami.exe"))
        self.assertEqual(whoami.parent_process_id, str(0x1f40))
        self.assertEqual(tree.parent_of(whoami).image, "C:\\Windows\\System32\\cmd.exe")

    def test_attack_chain_detected_without_sysmon(self):
        ids = _rule_ids(_analyze("security_only.jsonl"))
        for expected in ("EVTX-DISCOVERY-SEQ-01", "EVTX-C2-TRANSFER-01",
                         "EVTX-EXEC-ENCODED-PS-01", "EVTX-DEFENSE-LOGCLEAR-01"):
            self.assertIn(expected, ids)

    def test_encoded_payload_is_decoded_and_searched(self):
        result = _analyze("security_only.jsonl")
        enc = next(f for f in result.findings if f.rule_id == "EVTX-EXEC-ENCODED-PS-01")
        self.assertIn("DownloadString", enc.evidence["decoded"])
        transfers = [f for f in result.findings if f.rule_id == "EVTX-C2-TRANSFER-01"]
        self.assertEqual(len(transfers), 2)          # certutil + the hidden DownloadString

    def test_logon_ids_match_across_case(self):
        events = parse_jsonl_file(_p("security_only.jsonl"))
        self.assertGreaterEqual(len(events_for_logon_id(events, "0x5A1F00")), 6)

    def test_ipv4_mapped_private_address_is_internal(self):
        self.assertTrue(is_private_or_reserved_ip("::ffff:10.0.0.5"))
        self.assertFalse(is_private_or_reserved_ip("::ffff:198.51.100.23"))

    def test_mitre_attached_to_findings(self):
        result = _analyze("rdp_brute_force.jsonl")
        self.assertTrue(all(f.mitre for f in result.findings))


class TestDefenseEvasion(unittest.TestCase):
    def test_log_cleared_xml(self):
        result = _analyze("log_cleared.xml")
        self.assertEqual(sorted(f.title for f in result.findings),
                         ["Security event log cleared", "System event log cleared"])
        self.assertTrue(all(f.evidence["cleared_by"].endswith("mr.backd00r") for f in result.findings))

    def test_script_block_markers(self):
        result = _analyze("powershell_scriptblocks.xml")
        hits = [f for f in result.findings if f.rule_id == "EVTX-EXEC-PSSUSPICIOUS-01"]
        self.assertEqual(len(hits), 2)                # AMSI bypass + Mimikatz, not the admin block
        self.assertTrue(all(f.severity == "critical" for f in hits))

    def test_single_weak_marker_does_not_fire(self):
        e = EventRecord(index=0, event_id=1, channel="Sysmon", ts=1.0,
                        data={"Image": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                              "CommandLine": "powershell -NoProfile -File C:\\scripts\\backup.ps1"})
        self.assertNotIn("EVTX-EXEC-PSSUSPICIOUS-01", {f.rule_id for f in run_detectors([e], Config())})

    def test_decode_powershell_command(self):
        import base64
        from evtxkit.models import decode_powershell_command
        blob = base64.b64encode("whoami /all".encode("utf-16-le")).decode()
        self.assertEqual(decode_powershell_command(f"powershell -EncodedCommand {blob}"), "whoami /all")
        self.assertEqual(decode_powershell_command(f"pwsh /ec {blob}"), "whoami /all")
        self.assertEqual(decode_powershell_command("powershell -ExecutionPolicy Bypass"), "")

    def test_clean_baselines_still_zero(self):
        for name in ("clean_baseline.jsonl", "clean_baseline_ConsoleHost_history.txt"):
            self.assertEqual(_analyze(name).findings, [], name)


if __name__ == "__main__":
    unittest.main(verbosity=2)
