"""
Firewall ACL rule generation (Wireshark: Traffic Analysis, "Actionable
Results") -- turn findings into ready-to-drop rules for the same set of
targets Wireshark itself supports: Netfilter/iptables, Cisco IOS
(standard/extended), pf, and Windows Firewall (netsh).

This intentionally only ever generates *deny* rules scoped to the specific
IPs implicated by a finding -- never a broad allow-list -- so pasting the
output into a device without review can't accidentally open anything.
"""

from __future__ import annotations

from .models import Finding

SUPPORTED_TARGETS = ("iptables", "cisco_ios", "pf", "netsh")


#  Only these evidence keys consistently name the *offending* host across
#  every detector -- "dst"/"scanned"/"server"/"victims"/"hosts_probed"/
#  "targets_probed" all name the *target* of the bad traffic instead, and
#  including those would generate a rule blocking the victim, not the
#  attacker. ARP/MITM findings that only ever identify the attacker by MAC
#  (no stable IP of their own) correctly produce no IP rule here -- that's
#  a real limitation of IP-based ACLs against L2 spoofing, not a bug.
_ATTACKER_KEYS = ("src", "prober", "client")


def _implicated_ips(findings: list[Finding]) -> list[str]:
    ips: list[str] = []
    for f in findings:
        for key in _ATTACKER_KEYS:
            val = f.evidence.get(key)
            if isinstance(val, str) and _looks_ip(val) and val not in ips:
                ips.append(val)
    return ips


def _looks_ip(s: str) -> bool:
    """IPv4 or IPv6 literal (captures are dissected for IPv6 now too)."""
    import ipaddress
    try:
        ipaddress.ip_address(s)
        return True
    except ValueError:
        return False


def generate_acl(findings: list[Finding], target: str, min_severity: str = "medium") -> str:
    if target not in SUPPORTED_TARGETS:
        raise ValueError(f"Unknown ACL target {target!r}; supported: {', '.join(SUPPORTED_TARGETS)}")

    from .models import SEVERITY_ORDER
    floor = SEVERITY_ORDER.get(min_severity, 0)
    relevant = [f for f in findings if f.severity_rank >= floor]
    ips = _implicated_ips(relevant)
    if not ips:
        return f"# No {target} rules generated -- no findings at or above severity {min_severity!r}."

    lines = [f"# Auto-generated by trafkit -- {len(ips)} host(s) implicated in "
             f"{len(relevant)} finding(s) at severity >= {min_severity}.",
             "# Review before deploying. Source: trafkit acl."]

    v4 = [ip for ip in ips if ":" not in ip]
    v6 = [ip for ip in ips if ":" in ip]
    if target == "iptables":
        for ip in v4:
            lines.append(f"iptables -A INPUT -s {ip} -j DROP")
            lines.append(f"iptables -A FORWARD -s {ip} -j DROP")
        for ip in v6:
            lines.append(f"ip6tables -A INPUT -s {ip} -j DROP")
            lines.append(f"ip6tables -A FORWARD -s {ip} -j DROP")
    elif target == "cisco_ios":
        # An extended ACL ends in an implicit "deny any": without the final
        # permit, applying the deny list would drop ALL traffic on the
        # interface. And an access-group REPLACES the interface's current ACL.
        lines.append("! NOTE: applying an access-group replaces any ACL already on the interface.")
        lines.append("! If one exists, merge these deny lines into it (above its permits) instead.")
        if v4:
            lines.append("ip access-list extended TRAFKIT-BLOCK")
            for ip in v4:
                lines.append(f" deny ip host {ip} any")
            lines.append(" permit ip any any")
            lines.append("!")
        if v6:
            lines.append("ipv6 access-list TRAFKIT-BLOCK-V6")
            for ip in v6:
                lines.append(f" deny ipv6 host {ip} any")
            lines.append(" permit ipv6 any any")
            lines.append("!")
        lines.append("interface <apply-to-interface>")
        if v4:
            lines.append(" ip access-group TRAFKIT-BLOCK in")
        if v6:
            lines.append(" ipv6 traffic-filter TRAFKIT-BLOCK-V6 in")
    elif target == "pf":
        for ip in ips:
            lines.append(f"block drop in quick from {ip} to any")
    elif target == "netsh":
        for i, ip in enumerate(ips, start=1):
            lines.append(
                f'netsh advfirewall firewall add rule name="trafkit-block-{i}" '
                f'dir=in action=block remoteip={ip}'
            )

    return "\n".join(lines) + "\n"
